all:
	g++ -I ../gpio_library -I ../pwm \
	main.cpp \
	motors.cpp \
	../gpio_library/libbbgpio.a \
	../pwm/libpwm.a \
	-o my_program
#	g++ -I ../gpio_library     main.cpp     motors.cpp     ../gpio_library/libbbgpio.a     -o my_program
